apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodeapp
spec:
  minReadySeconds: 30
  selector: 
    matchLabels:
      app: nodeapp
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: pardeep889/pracapp:0106120
        ports:
        - containerPort: 8080
